from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_cfg(package="samplerate", uselib_store="samplerate", args="--cflags --libs"):
        return False
    return True

configure, build = plugin('resample', source=['resample.c'],
                          configure=plugin_configure,
                          libs=["samplerate"])
