from waftools.plugin import plugin

def plugin_configure(conf):
    conf.check_cfg(package="shout", args="--cflags --libs",
            uselib_store="shout")
    conf.check_cfg(package="ogg", args="--cflags --libs",
            uselib_store="ogg")
    conf.check_cfg(package="opus", args="--cflags --libs",
            uselib_store="opus")

configure, build = plugin('ices', configure=plugin_configure,
                          libs=["shout", "opus", "ogg", "socket"],
                          output_prio=10)
